name: Doppler CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  doppler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        run: |
          curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sudo sh

      - name: Login to Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}
        run: doppler login --token "$DOPPLER_TOKEN"

      - name: Run Doppler test
        run: |
          doppler run --doppler-config=development -- \
          bash -lc 'echo doppler test OK'

